<?php

namespace AppBundle\Repository;

/**
 * listeNoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class listeNoteRepository extends \Doctrine\ORM\EntityRepository
{
}
