AppBundle\Entity\Etudiant:
    type: entity
    table: etudiant
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        prenom:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        uniqId:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: uniq_id
        email:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        dateNaissance:
            type: date
            nullable: false
            column: date_naissance
        lieuNaissance:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
            column: lieu_naissance
        adresse:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        telephone:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        niveau:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        note:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        image:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
                default: 'NULL'
    lifecycleCallbacks: {  }
